<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="6" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-22T23:26:13 IST" name="Suite" finished-at="2025-02-22T23:26:45 IST" duration-ms="31171">
    <groups>
      <group name="Smoke">
        <method signature="ErrorValidation.verifyLoginError()[pri:0, instance:Cognizant.Test.ErrorValidation@14f232c4]" name="verifyLoginError" class="Cognizant.Test.ErrorValidation"/>
      </group> <!-- Smoke -->
      <group name="Purchasedataprovider">
        <method signature="FrameWorkBuildTest.submitOrder(java.util.HashMap)[pri:0, instance:Cognizant.Test.FrameWorkBuildTest@21be3395]" name="submitOrder" class="Cognizant.Test.FrameWorkBuildTest"/>
      </group> <!-- Purchasedataprovider -->
    </groups>
    <test started-at="2025-02-22T23:26:13 IST" name="ErrorValidation" finished-at="2025-02-22T23:26:22 IST" duration-ms="9089">
      <class name="Cognizant.Test.ErrorValidation">
        <test-method is-config="true" signature="launch()[pri:0, instance:Cognizant.Test.ErrorValidation@14f232c4]" started-at="2025-02-22T23:26:13 IST" name="launch" finished-at="2025-02-22T23:26:18 IST" duration-ms="4065" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method retried="true" signature="verifyLoginError()[pri:0, instance:Cognizant.Test.ErrorValidation@14f232c4]" started-at="2025-02-22T23:26:18 IST" name="verifyLoginError" finished-at="2025-02-22T23:26:18 IST" duration-ms="653" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect ema or password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect ema or password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Cognizant.Test.ErrorValidation.verifyLoginError(ErrorValidation.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginError -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:Cognizant.Test.ErrorValidation@14f232c4]" started-at="2025-02-22T23:26:18 IST" name="closeBrowser" finished-at="2025-02-22T23:26:19 IST" duration-ms="400" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launch()[pri:0, instance:Cognizant.Test.ErrorValidation@14f232c4]" started-at="2025-02-22T23:26:19 IST" name="launch" finished-at="2025-02-22T23:26:22 IST" duration-ms="2995" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method signature="verifyLoginError()[pri:0, instance:Cognizant.Test.ErrorValidation@14f232c4]" started-at="2025-02-22T23:26:22 IST" name="verifyLoginError" finished-at="2025-02-22T23:26:22 IST" duration-ms="525" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect ema or password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect ema or password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Cognizant.Test.ErrorValidation.verifyLoginError(ErrorValidation.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginError -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:Cognizant.Test.ErrorValidation@14f232c4]" started-at="2025-02-22T23:26:22 IST" name="closeBrowser" finished-at="2025-02-22T23:26:22 IST" duration-ms="133" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- Cognizant.Test.ErrorValidation -->
    </test> <!-- ErrorValidation -->
    <test started-at="2025-02-22T23:26:13 IST" name="SubmitOrder" finished-at="2025-02-22T23:26:45 IST" duration-ms="31171">
      <class name="Cognizant.Test.FrameWorkBuildTest">
        <test-method is-config="true" signature="launch()[pri:0, instance:Cognizant.Test.FrameWorkBuildTest@21be3395]" started-at="2025-02-22T23:26:14 IST" name="launch" finished-at="2025-02-22T23:26:24 IST" duration-ms="10468" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Cognizant.Test.FrameWorkBuildTest@21be3395]" started-at="2025-02-22T23:26:24 IST" name="submitOrder" data-provider="hasdata" finished-at="2025-02-22T23:26:29 IST" duration-ms="4959" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sanrahul324@#, product=ADIDAS ORIGINAL, Email=santhosh42@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:Cognizant.Test.FrameWorkBuildTest@21be3395]" started-at="2025-02-22T23:26:29 IST" name="closeBrowser" finished-at="2025-02-22T23:26:29 IST" duration-ms="230" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launch()[pri:0, instance:Cognizant.Test.FrameWorkBuildTest@21be3395]" started-at="2025-02-22T23:26:29 IST" name="launch" finished-at="2025-02-22T23:26:33 IST" duration-ms="3400" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Cognizant.Test.FrameWorkBuildTest@21be3395]" started-at="2025-02-22T23:26:33 IST" name="submitOrder" data-provider="hasdata" finished-at="2025-02-22T23:26:38 IST" duration-ms="5516" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sanrahul324@#, product=IPHONE 13 PRO, Email=santhosh62@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:Cognizant.Test.FrameWorkBuildTest@21be3395]" started-at="2025-02-22T23:26:38 IST" name="closeBrowser" finished-at="2025-02-22T23:26:39 IST" duration-ms="227" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launch()[pri:0, instance:Cognizant.Test.FrameWorkBuildTest@21be3395]" started-at="2025-02-22T23:26:39 IST" name="launch" finished-at="2025-02-22T23:26:44 IST" duration-ms="5036" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method signature="VerifyOrderDetails()[pri:0, instance:Cognizant.Test.FrameWorkBuildTest@21be3395]" started-at="2025-02-22T23:26:44 IST" name="VerifyOrderDetails" finished-at="2025-02-22T23:26:44 IST" depends-on-methods="Cognizant.Test.FrameWorkBuildTest.submitOrder" duration-ms="780" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyOrderDetails -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:Cognizant.Test.FrameWorkBuildTest@21be3395]" started-at="2025-02-22T23:26:44 IST" name="closeBrowser" finished-at="2025-02-22T23:26:45 IST" duration-ms="218" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- Cognizant.Test.FrameWorkBuildTest -->
    </test> <!-- SubmitOrder -->
  </suite> <!-- Suite -->
</testng-results>
